spring:
  config:
    import: "aws-parameterstore:/config/camp-health-app/"
  cloud:
    aws:
      parameterstore:
        enabled: true
      region:
        static: ap-northeast-2
  profiles:
    active: local
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "health"