spring:

  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: "my-member-profile-bucket-2026"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  config:
    import:
      - "optional:aws-parameterstore:/config/camp-health-app/"
      - "optional:aws-parameterstore:/camp-health-app/prod/"

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: true

info:
  app:
    name: "Member Profile Service"
    team-name: "${team-name}"
    message: "${APP_MESSAGE}"

logging:
  level:
    root: INFO